name: CI
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: npm install --no-optional --no-audit --no-fund --progress=false
      - run: npm run dist
      - run: npm run report:size
      - run: npm run report:package
      - run: npm run test:ci
      - run: base64 < ./tests/integration/__image_snapshots__/__diff_output__/* || true
      - run: npm run test:performance
      - run: npx danger ci --verbose
        if: ${{ github.event_name == 'pull_request' }}
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mv coverage/lcov-report build || true
      - run: cat ./coverage/lcov.info | npx coveralls || true
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: public
          retention-days: 1
