name: CI
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: npm install --no-optional --no-audit --no-fund --progress=false
      - run: npm run dist
      - run: npm run report:size
      - run: npm run report:package
      - run: npm run test:performance
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: public
          retention-days: 1
